@startuml
participant c as "client"
participant cfs as "client-facing server"
participant bs as "backend server"

skinparam SequenceMessageAlign direction

c -> cfs: ClientHelloOuter\n+<inner_servername>\n
cfs -> bs: ClientHelloInner\n+inner_servername
bs -> cfs: ServerHello\n+<sech_accept_confirmation>
cfs --> c: ServerHello
@enduml

